version: '3.9'

services:
  app:
    container_name: outbox_app
    image: node:19-buster-slim
    restart: always
    depends_on:
        - db
        - redis
    volumes:
        - ./be/:/app/
    ports:
        - "3333:3000"
    environment:
        SECRET_PATH: "/run/secrets/root_"
        MONGO_URI: "db"
        REDIS_URI: "redis"
        REDIS_PORT: "6379"
    working_dir: /app
    command: bash -c "npm install && npm run docker"
    secrets:
      - root_pw
  db:
    container_name: outbox_mysql
    build:
        context: ./docker/mysql
        dockerfile: mysql.Dockerfile
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
        - "mysql-data:/var/lib/mysql"
    environment:
      TZ: "Asia/Seoul"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_pw
      MYSQL_DATABASE: outbox
      MYSQL_USER: osmDB
      MYSQL_PASSWORD_FILE: /run/secrets/osmDB_pw
    secrets:
      - root_pw
      - osmDB_pw

  redis:
    container_name: outbox_redis
    image: redis:7.0.5-bullseye
    restart: unless-stopped
    command: redis-server --requirepass "doredis8082" --port 6379
    ports:
      - "6379:6379"
    environment:
        TZ: "Asia/Seoul"

secrets:
  root_pw:
    file: ./docker/mysql/mysql_root_pw
  osmDB_pw:
    file: ./docker/mysql/mysql_osmDB_pw

volumes:
    mysql-data: