CREATE DATABASE IF NOT EXISTS outbox;
CREATE TABLE IF NOT EXISTS outbox.user (
    Name VARCHAR(30) NOT NULL,
    pwd VARCHAR(255) NOT NULL,
    Refresh_token VARCHAR(255),
    Email VARCHAR(50) PRIMARY KEY,
    Role TINYINT NOT NULL,
    Position TINYINT,
    C_DATE DATE NOT NULL
) CHARSET=utf8;